### PR TITLE
Test fix #436 with (non-atomic) simple pipeline.

### LINKED ISSUE #436: Errors in an atomic Pipeline leave unread data that leaks to the next command
When running commands in a `redis::pipe()::atomic()` transaction, if Redis returns an error for one of the commands (e.g. `READONLY` instead of `QUEUED`), the results for the remaining commands are not read and therefore erroneously remain there in the socket buffer. They will be returned by any subsequent command.

The following program illustrates the problem:

```
use redis::{Commands, RedisResult};

fn test() -> RedisResult<()> {
    let client = redis::Client::open("redis://localhost")?;
    let mut con = client.get_connection()?;

    // Ensure Redis is not currently a replicaof
    redis::cmd("replicaof").arg("no").arg("one").query(&mut con)?;

    con.set("x", "42")?;

    // Make Redis a replica of a nonexistent master, thereby making it read-only.
    redis::cmd("replicaof").arg("1.1.1.1").arg("1").query(&mut con)?;

    // Ensure that a write command fails with a READONLY error
    let result: RedisResult<Option<(String,)>> = redis::pipe().atomic()
        .set("x", "abc").ignore()
        .get("x")
        .query(&mut con);

    let err = result.unwrap_err().to_string();
    assert!(err.starts_with("READONLY"));

    // Here we get erroneous leftover results from the previous pipeline!
    for _ in 0..3 {
        let x: RedisResult<String> = con.get("x");
        println!("{:?}", x);
    }

    Ok(())
}

fn main() {
    test().unwrap();
}
```

The expected output:
```
Ok("42")
Ok("42")
Ok("42")
```

The actual output:
```
Ok("QUEUED")
Err(An error was signalled by the server: Transaction discarded because of previous errors.)
Ok("42")
```

When using a standard `Pipeline` without `atomic`, this works as intended.

The problem seems to be that the code in `req_packed_commands` returns with the `?` operator on the first error encountered, instead of first reading the rest of the results.

### PR DESCRIPTION
**Pull request by yoav-steinberg**

### CODE REVIEW

**Comment by yoav-steinberg** [comment]
I verified this test fails (we get `"y-value"` instead of `"x-value"`) before fix #436. This means the original bug was for all pipelines not only atomic ones.

File: src/types.rs [hunk 1]
```diff
@@ -385,6 +388,7 @@ impl RedisError {
             ErrorKind::IoError => "I/O error",
             ErrorKind::ExtensionError => "extension error",
             ErrorKind::ClientError => "client error",
+            ErrorKind::ReadOnly => "read-only",
```
Comment (gavrie) [inline src/types.rs:391]:
```suggestion
            ErrorKind::ReadOnly => "read-only error",
```

File: src/parser.rs [hunk 2]
```diff
@@ -129,6 +129,7 @@ where
                         "CLUSTERDOWN" => ErrorKind::ClusterDown,
                         "CROSSSLOT" => ErrorKind::CrossSlot,
                         "MASTERDOWN" => ErrorKind::MasterDown,
+                        "READONLY" => ErrorKind::ReadOnly,
```
Comment (gavrie) [inline src/parser.rs:132]: Yup, this definitely makes things cleaner.

**Review by gavrie — APPROVED** [review]

**Review by Marwes — APPROVED** [review]
