### PR TITLE
Fix #436: Read remaining responses in case of an error

### LINKED ISSUE #436: Errors in an atomic Pipeline leave unread data that leaks to the next command
When running commands in a `redis::pipe()::atomic()` transaction, if Redis returns an error for one of the commands (e.g. `READONLY` instead of `QUEUED`), the results for the remaining commands are not read and therefore erroneously remain there in the socket buffer. They will be returned by any subsequent command.

The following program illustrates the problem:

```
use redis::{Commands, RedisResult};

fn test() -> RedisResult<()> {
    let client = redis::Client::open("redis://localhost")?;
    let mut con = client.get_connection()?;

    // Ensure Redis is not currently a replicaof
    redis::cmd("replicaof").arg("no").arg("one").query(&mut con)?;

    con.set("x", "42")?;

    // Make Redis a replica of a nonexistent master, thereby making it read-only.
    redis::cmd("replicaof").arg("1.1.1.1").arg("1").query(&mut con)?;

    // Ensure that a write command fails with a READONLY error
    let result: RedisResult<Option<(String,)>> = redis::pipe().atomic()
        .set("x", "abc").ignore()
        .get("x")
        .query(&mut con);

    let err = result.unwrap_err().to_string();
    assert!(err.starts_with("READONLY"));

    // Here we get erroneous leftover results from the previous pipeline!
    for _ in 0..3 {
        let x: RedisResult<String> = con.get("x");
        println!("{:?}", x);
    }

    Ok(())
}

fn main() {
    test().unwrap();
}
```

The expected output:
```
Ok("42")
Ok("42")
Ok("42")
```

The actual output:
```
Ok("QUEUED")
Err(An error was signalled by the server: Transaction discarded because of previous errors.)
Ok("42")
```

When using a standard `Pipeline` without `atomic`, this works as intended.

The problem seems to be that the code in `req_packed_commands` returns with the `?` operator on the first error encountered, instead of first reading the rest of the results.

### PR DESCRIPTION
**Pull request by gavrie**
When a `MULTI/EXEC` transaction fails due to errors, the remaining responses should be read instead of returning early. This fixes #436.

### CODE REVIEW

File: src/connection.rs [hunk 1]
```diff
@@ -818,11 +818,18 @@ impl ConnectionLike for Connection {
...
         let mut rv = vec![];
         for idx in 0..(offset + count) {
-            let item = self.read_response()?;
-            if idx >= offset {
-                rv.push(item);
+            // When processing a transaction, some responses may be errors.
+            // We need to keep processing the rest of the responses in that case,
+            // so bailing early with `?` would not be correct.
+            // See: https://github.com/mitsuhiko/redis-rs/issues/436
+            let response = self.read_response();
```
Comment (Marwes) [inline src/connection.rs:825]: Any errors occuring will just be lost here, I'd expect an error (probably the first?) to still be returned after consuming the remaining commands.

**Review by Marwes — CHANGES_REQUESTED** [review]
A test would be nice to have if you can. The (basic) async connection could also use the same fix.

**Comment by gavrie** [comment]
> A test would be nice to have if you can. The (basic) async connection could also use the same fix.

@Marwes the ticket (#436) includes my test code that triggers this. Would you like me to convert it to an actual test?
I'll look at the async version as well.

File: src/connection.rs (hunk 1 above)
Comment (gavrie) [reply src/connection.rs:825]: @Marwes the error from the failed transaction will be returned (`Transaction discarded because of previous errors.`). I thought of returning a vector of `Results`, but that would change the API quite a bit.

Comment (Marwes) [reply src/connection.rs:825]: `Transaction discarded because of previous errors.` is a pretty bad error though. Chances are the first error that occured is the one with the most information returning that seems to make the most sense to me.

Comment (gavrie) [reply src/connection.rs:825]: Very well, I'll proceed in that direction.

Comment (gavrie) [reply src/connection.rs:826]: I changed the code as suggested -- the first error is now returned.

**Comment by gavrie** [comment]
I've added a test that shows the bug and verifies the fix.

**Comment by gavrie** [comment]
...and I've added the async test + fix as well.

**Comment by gavrie** [comment]
I see that the Windows CI is broken because of the `replicaof` command; it probably uses an old Redis version. Will try `slaveof` instead.

**Comment by gavrie** [comment]
Ok, that fixe it.

**Review by Marwes — APPROVED** [review]

**Comment by Marwes** [comment]
Thanks!

**Comment by gavrie** [comment]
> Thanks!

Thank you @Marwes for the quick responses! Now we won't need to use a forked version...
